export const SHOULD_SHOW_FIRST_DETAIL_BOX = 'SHOULD_SHOW_FIRST_DETAIL_BOX'
export const SHOULD_SHOW_CAMERA_VIEW = 'SHOULD_SHOW_CAMERA_VIEW'
export const RESET_DETAIL_BOXES_REDUX_STATE = 'RESET_DETAIL_BOXES_REDUX_STATE'